name: Wounds in the Sky
favicon: null
layout_spectrum: 0.45132
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121315'
    - '#fefefe'
    - '#446694'
    - '#fe5941'
    - '#fead53'
  brandStrength: 0.75
  lightness: 0.16663856571540236
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
